#!/bin/bash
set -e

# Ожидается, что .env переменные проброшены в контейнер (через env_file: .env в docker-compose)

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
-- Расширения
CREATE EXTENSION IF NOT EXISTS vector;

-- Схемы
CREATE SCHEMA IF NOT EXISTS backend;
CREATE SCHEMA IF NOT EXISTS bot;
CREATE SCHEMA IF NOT EXISTS vectors;
CREATE SCHEMA IF NOT EXISTS settings;

-- Пользователи с изолированными правами
CREATE USER ${DB_USER_BACKEND} WITH PASSWORD '${DB_PASSWORD_BACKEND}';
GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DB_USER_BACKEND};
GRANT USAGE, CREATE ON SCHEMA backend TO ${DB_USER_BACKEND};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA settings TO ${DB_USER_BACKEND};

CREATE USER ${DB_USER_BOT} WITH PASSWORD '${DB_PASSWORD_BOT}';
GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DB_USER_BOT};
GRANT USAGE, CREATE ON SCHEMA bot TO ${DB_USER_BOT};

CREATE USER ${DB_USER_AI} WITH PASSWORD '${DB_PASSWORD_AI}';
GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DB_USER_AI};
GRANT USAGE, CREATE ON SCHEMA vectors TO ${DB_USER_AI};

CREATE USER ${DB_USER_CRON} WITH PASSWORD '${DB_PASSWORD_CRON}';
GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DB_USER_CRON};
GRANT USAGE, CREATE ON SCHEMA settings TO ${DB_USER_CRON};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA settings TO ${DB_USER_CRON};

CREATE USER ${DB_USER_BOT_NOTIFICATION} WITH PASSWORD '${DB_PASSWORD_BOT_NOTIFICATION}';
GRANT CONNECT ON DATABASE ${DB_NAME} TO ${DB_USER_BOT_NOTIFICATION};
GRANT USAGE ON SCHEMA bot TO ${DB_USER_BOT_NOTIFICATION};

-- Выдаем права на будущие таблицы ДО их создания, так как таблицы теперь создаются миграциями
ALTER DEFAULT PRIVILEGES IN SCHEMA settings GRANT ALL PRIVILEGES ON TABLES TO ${DB_USER_CRON};
ALTER DEFAULT PRIVILEGES IN SCHEMA settings GRANT ALL PRIVILEGES ON TABLES TO ${DB_USER_BACKEND};
ALTER DEFAULT PRIVILEGES IN SCHEMA bot GRANT ALL PRIVILEGES ON TABLES TO ${DB_USER_BOT};
ALTER DEFAULT PRIVILEGES IN SCHEMA bot GRANT SELECT ON TABLES TO ${DB_USER_BOT_NOTIFICATION};
EOSQL
