/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdGroupSchema extends BaseModel {
  static $columns = [
    'campaignPk',
    'createdAt',
    'groupId',
    'id',
    'name',
    'source',
    'status',
    'updatedAt',
  ] as const
  $columns = AdGroupSchema.$columns
  @column()
  declare campaignPk: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare groupId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare source: string
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AdSchema extends BaseModel {
  static $columns = [
    'adId',
    'adPlatform',
    'conditionId',
    'conditionName',
    'createdAt',
    'groupPk',
    'id',
    'source',
    'status',
    'text',
    'title',
    'updatedAt',
  ] as const
  $columns = AdSchema.$columns
  @column()
  declare adId: string
  @column()
  declare adPlatform: string | null
  @column()
  declare conditionId: string | null
  @column()
  declare conditionName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare groupPk: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare source: string
  @column()
  declare status: string | null
  @column()
  declare text: string | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CampaignSchema extends BaseModel {
  static $columns = [
    'campaignId',
    'createdAt',
    'id',
    'name',
    'source',
    'state',
    'status',
    'type',
    'updatedAt',
  ] as const
  $columns = CampaignSchema.$columns
  @column()
  declare campaignId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare source: string
  @column()
  declare state: string | null
  @column()
  declare status: string | null
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CrmPipelineSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isMain', 'name', 'sort', 'source', 'updatedAt'] as const
  $columns = CrmPipelineSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isMain: boolean | null
  @column()
  declare name: string
  @column()
  declare sort: number | null
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CrmRecordSchema extends BaseModel {
  static $columns = [
    'adId',
    'adPk',
    'budget',
    'campaignId',
    'campaignPk',
    'city',
    'comment',
    'companyName',
    'createdAt',
    'dealId',
    'dealName',
    'dealStage',
    'groupId',
    'groupPk',
    'id',
    'isDeleted',
    'pipelineId',
    'price',
    'product',
    'rawIds',
    'recordClosedTaskAt',
    'recordCreatedAt',
    'recordCreatedByName',
    'recordNextTaskAt',
    'recordUpdatedAt',
    'recordUpdatedByName',
    'referrer',
    'region',
    'saleFunnel',
    'source',
    'statusId',
    'tagDeal',
    'updatedAt',
    'website',
  ] as const
  $columns = CrmRecordSchema.$columns
  @column()
  declare adId: string | null
  @column()
  declare adPk: number | null
  @column()
  declare budget: string | null
  @column()
  declare campaignId: string | null
  @column()
  declare campaignPk: number | null
  @column()
  declare city: string | null
  @column()
  declare comment: string | null
  @column()
  declare companyName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dealId: string | null
  @column()
  declare dealName: string | null
  @column()
  declare dealStage: string | null
  @column()
  declare groupId: string | null
  @column()
  declare groupPk: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDeleted: boolean | null
  @column()
  declare pipelineId: bigint | number | null
  @column()
  declare price: string | null
  @column()
  declare product: string | null
  @column()
  declare rawIds: string | null
  @column.dateTime()
  declare recordClosedTaskAt: DateTime | null
  @column.dateTime()
  declare recordCreatedAt: DateTime | null
  @column()
  declare recordCreatedByName: string | null
  @column.dateTime()
  declare recordNextTaskAt: DateTime | null
  @column.dateTime()
  declare recordUpdatedAt: DateTime | null
  @column()
  declare recordUpdatedByName: string | null
  @column()
  declare referrer: string | null
  @column()
  declare region: string | null
  @column()
  declare saleFunnel: string | null
  @column()
  declare source: string | null
  @column()
  declare statusId: bigint | number | null
  @column()
  declare tagDeal: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare website: string | null
}

export class CrmStatusSchema extends BaseModel {
  static $columns = [
    'color',
    'createdAt',
    'id',
    'name',
    'pipelineId',
    'sort',
    'source',
    'type',
    'updatedAt',
  ] as const
  $columns = CrmStatusSchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare pipelineId: bigint | number
  @column()
  declare sort: number | null
  @column()
  declare source: string
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DailyStatSchema extends BaseModel {
  static $columns = [
    'adPk',
    'avgCpc',
    'avgCpm',
    'clicks',
    'cost',
    'createdAt',
    'ctr',
    'date',
    'id',
    'impressions',
    'updatedAt',
  ] as const
  $columns = DailyStatSchema.$columns
  @column()
  declare adPk: number | null
  @column()
  declare avgCpc: string | null
  @column()
  declare avgCpm: string
  @column()
  declare clicks: number
  @column()
  declare cost: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare ctr: string
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare impressions: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class IntegrationMetadatumSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'credentials',
    'historicalSyncState',
    'historicalSyncedUntil',
    'id',
    'lastError',
    'lastSuccessSyncDate',
    'lastTimestamp',
    'referenceSyncPhase',
    'source',
    'syncStartDate',
    'syncStatus',
    'updatedAt',
  ] as const
  $columns = IntegrationMetadatumSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare credentials: string | null
  @column()
  declare historicalSyncState: any | null
  @column.date()
  declare historicalSyncedUntil: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare lastSuccessSyncDate: DateTime | null
  @column()
  declare lastTimestamp: string | null
  @column()
  declare referenceSyncPhase: string | null
  @column()
  declare source: string
  @column.date()
  declare syncStartDate: DateTime | null
  @column()
  declare syncStatus: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SyncLogSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'level', 'message', 'metadata', 'source'] as const
  $columns = SyncLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: string
  @column()
  declare message: string
  @column()
  declare metadata: any | null
  @column()
  declare source: string
}
