/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class IntegrationMetadatumSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'currentSyncDate',
    'id',
    'lastError',
    'lastSyncAt',
    'lastTimestamp',
    'referenceSyncPhase',
    'source',
    'syncStartDate',
    'syncStatus',
    'token',
    'updatedAt',
  ] as const
  $columns = IntegrationMetadatumSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare currentSyncDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare lastSyncAt: DateTime | null
  @column()
  declare lastTimestamp: string | null
  @column()
  declare referenceSyncPhase: string | null
  @column()
  declare source: string
  @column.date()
  declare syncStartDate: DateTime | null
  @column()
  declare syncStatus: string | null
  @column()
  declare token: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
