/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  sync: {
    SyncStatus: () => import('#controllers/sync/sync_status_controller'),
    YandexIntegration: () => import('#controllers/sync/yandex_integration_controller'),
  },
}
